/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_pri_jobqueue.h - structures and function declarations for unit tests
 * of pri_jobqueue functions.
 */  
#ifndef _TEST_PRI_JOBQUEUE_H
#define _TEST_PRI_JOBQUEUE_H
#include "munit/munit.h"

MunitResult test_pri_jobqueue_dummy(const MunitParameter params[],
    void* fixture);

static MunitTest tests[] = {
    { "/test_pri_jobqueue_dummy", test_pri_jobqueue_dummy, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_pri_jobqueue", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    

#endif