/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_jobqueue_common.h - structures and function declarations for
 * common unit tests of pri_jobqueue, ipc_jobqueue and sem_jobqueue functions.
 */  
#ifndef _TEST_JOBQUEUE_COMMON_H
#define _TEST_JOBQUEUE_COMMON_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit/munit.h"

// tests
MunitResult test_jq_dummy(void);
#endif